server:
  port: 17772

spring:
  application:
    name: gateway
  profiles:
    active: local
  config:
    import: optional:configserver:http://localhost:17771
  cloud:
    config:
      fail-fast: true