version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container-dev
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/conf.d:/wisoft/database/mysql/dev/conf.d
      - ./backup:/wisoft/database/mysql/dev/backup
