server:
  port: 17773

spring:
  application:
    name: apiexample
  profiles:
    active: local # local, dev, prod
  config:
    import: optional:configserver:http://localhost:17771
  cloud:
    config:
      fail-fast: true
