server:
  port: 17771

spring:
  application:
    name: config-service

  profiles:
    active: native # if config server target Native File System (Not Git)

  cloud:
    config:
      server:
        native:
          # Native File System Location (Not Git)
          # Local 실행시
#          search-locations: ./config-file
          # Dev 실행시
          search-locations: file:///wisoft/backend/dev/configserver/config-file
